# Generated by Django 5.2.7 on 2025-10-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("grocery", "Grocery"),
                    ("home_appliances", "Home Appliances"),
                    ("books", "Books"),
                    ("toys", "Toys"),
                    ("beauty", "Beauty"),
                ],
                default="electronics",
                max_length=50,
            ),
        ),
    ]
