# Generated by Django 5.2.7 on 2025-10-24 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.category",
            ),
        ),
    ]
