# Generated by Django 5.2.7 on 2025-10-24 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_product_category_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_fk",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.category"
            ),
        ),
    ]
