# Generated by Django 5.2.7 on 2025-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(default=dict),
        ),
    ]
